name: build

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Whether to run the workflow in dry-run mode'
        type: boolean
        required: false
        default: true
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      
      - name: Install dependencies
        run: npm clean-install

      - name: Lint code with standard
        run: npm run lint

      - name: Run tests
        run: npm test
